### ISSUE TITLE
Error : File not found: '/home/runner/work/_actions/education/autograding/v1/./dist/index.js'

### ISSUE THREAD

**Issue by profThiernesse** [education/autograding#100]
For a moment i have this error when launching autograding : 
File not found: '/home/runner/work/_actions/education/autograding/v1/./dist/index.js'

Also with old repository that's work previously.

**Comment by kabraambika** [comment]
I am also facing same issue.

**Comment by octosteve** [comment]
@profThiernesse This should be fixed now.

**Comment by profThiernesse** [comment]
Yes it is. Thanks for your response and fixing.
