### ISSUE TITLE
Bug: Recurring issue with the autograding process in GitHub Actions for GitHub Classroom after today's release

### ISSUE THREAD

**Issue by kabraambika** [education/autograding#101]
Hello,

Since the recent release of the autograding action, I have been experiencing consistent failures in every submission on GitHub. The GitHub Actions workflow is failing, and the error message is displayed as follows:
![image](https://github.com/education/autograding/assets/90600253/bb0b1228-c568-4b6f-aab5-7cba28c7d338)
![image](https://github.com/education/autograding/assets/90600253/f27a4b68-1b14-4674-999d-dde741240c60)

**Workflow file:**
![image](https://github.com/education/autograding/assets/90600253/201a0c36-066e-45be-9242-f0c1bf812eb4)
 

**Autograding.json:**
![image](https://github.com/education/autograding/assets/90600253/e72ad16b-3514-4a6f-9265-3fe703186147)

**Please feel free to provide insights, advice or potential workarounds.**

**Comment by profThiernesse** [comment]
I have the same issue

**Comment by jeffrafter** [comment]
I'm not sure of the issue (I'm not @ GitHub anymore) but it looks like there are two possible problems. The latest autograding should be using Node 16 but it looks like your action is running 12. Maybe that's okay, but it looks like it is not running (or not successfully running) the `npm run build` step. It almost looks like this is missing from the `units` step. https://github.com/education/autograding/blob/master/.github/workflows/ci.yml#L22 cc @octosteve

**Comment by kabraambika** [comment]
Thanks for the reply, @jeffrafter.
I would like to highlight that the autograding process was functioning properly yesterday, despite the deprecation of Node.js 12 as shown below.
![image](https://github.com/education/autograding/assets/90600253/2f7fcb39-dd73-4fda-99d0-48494ee54201)

**Comment by jisbruzzi** [comment]
I am seeing the same issue at the college class I teach: https://github.com/compiladores/
Failed runs:
- https://github.com/compiladores/tpo5_1c23-jisbruzzi/actions/runs/5204802152/jobs/9389490404
- https://github.com/compiladores/tpo5_1c23-jm-velazquez/actions/runs/5204636196/jobs/9389451373

**Comment by mingjun97** [comment]
Same issue here.

Last observed functional time:`2023-06-07T09:55:23-07:00`
Earliest observed malfunctions time: `2023-06-07T11:36:42-07:00`

![image](https://github.com/community/community/assets/15214491/25561e6d-4a57-472e-9178-6e046c60b8b5)

**Comment by octosteve** [comment]
Thanks for raising this! @jeffrafter thanks for the heads up.

**Comment by octosteve** [comment]
Rolled this back until we can figure out why the build process failed.

**Comment by octosteve** [comment]
Ok! This should be fixed now. Something was failing in the build script silently.

**Comment by kabraambika** [comment]
Thanks for quick response @octosteve. It's working now.

**Comment by octosteve** [comment]
Great! Thanks again.

**Comment by profThiernesse** [comment]
Thanks for response and fixing

Le jeu. 8 juin 2023, 01:46, Steven Nunez ***@***.***> a
écrit :
