### ISSUE TITLE
Export autograding grades

### ISSUE THREAD

**Issue by khatchad** [education/autograding#15]
Right now, I can see the points the students scored on the dashboard. But, more useful would be able to export a CSV of the grades so that I can import them into my Blackboard gradebook.

**Comment by jeffrafter** [comment]
This is a good suggestion, we've opened an issue internally to track this. The information is embedded in the check run for all of the Github Actions but it is pretty difficult to extract that. I think if we are able to add this functionality it would be in GitHub Classroom directly not in this action... so I'll close this for now.

**Comment by jfemiani** [comment]
Is there a way to check the status?

**Comment by jslingsby** [comment]
Since this is the first hit I got on a Google search I thought I should answer this issue to indicate that this functionality now exists. See https://education.github.community/t/introducing-easy-grade-downloading-for-classroom/69995
