### ISSUE TITLE
Auto-grading Support for Scala

### ISSUE THREAD

**Issue by vmaravind96** [education/autograding#57]
Hi team, 

In Grading and feedback, currently there is no option for running Scala tests. Kindly include feature for running tests in Scala. 

<img width="607" alt="image" src="https://user-images.githubusercontent.com/25263044/184711005-74a2ddee-60bd-4921-90ad-ca4ffe2e0afd.png">

Thanks !

**Comment by markpatterson27** [comment]
There's nothing special about the 'Run Java', 'Run Node', 'Run Python', etc options. They just prepopulate the run command field with a typical 'run tests' command for that language (i.e. for Java it's `gradle test`). You can just use the 'Run command' option and input your own command for running Scala tests.

I have no experience with using Scala, so I'm not sure if it's supported on the GitHub runner (You can find what software is pre-installed at this link: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md). You might need to use a custom workflow to setup Scala on the runner yourself before calling the autograding action. In this case, include `.github/workflows/classroom.yml` and `.github/classroom/autograding.json` in your template repo and don't touch the classroom interface for autograding tests.

**Comment by vmaravind96** [comment]
Perfect thanks! I see `sbt` pre-installed in the link that you have given. We use sbt to run Scala tests. It worked as well when I execute the command.
