### ISSUE TITLE
Node 12 Deprecation

### ISSUE THREAD

**Issue by dgrahn** [education/autograding#60]
Node 12 is being deprecated. This action needs to be updated to Node 16.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by markpatterson27** [comment]
I have a PR for this #54

**Comment by cfries** [comment]
There is still a warning message that Node 12 is depracated when running autograding. This message is maybe confusing for students. Why is this still open?

**Comment by michaelee** [comment]
Autograding with automated grade collection on GitHub Classroom is broken for now till this is resolved, right?

**Comment by octosteve** [comment]
@dgrahn This is fixed now.
